# Generated by Django 5.1.7 on 2025-10-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('ninguna', 'Ninguna'), ('baile', 'Baile'), ('bicicleta', 'Bicicleta'), ('caminata', 'Caminata'), ('futbol', 'Futbol'), ('gimnasio', 'Gimnasio'), ('golf', 'Golf'), ('hockey', 'Hockey'), ('kinesio', 'Kinesio'), ('patin', 'Patin'), ('pilates', 'Pilates'), ('rugby', 'Rugby'), ('yoga', 'Yoga'), ('zumba', 'Zumba')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('comidas', 'Comidas'), ('estacional', 'Estacional'), ('insectos', 'Insectos'), ('medicamentos', 'Medicamentos')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anticoagulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('si', 'Si')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnticoagulanteMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguno', 'Ninguno'), ('acetilsalicilico', 'Acetilsalicílico'), ('aspirina', 'Aspirina'), ('heparina', 'Heparina')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colesterol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('si', 'Sí')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColesterolMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguno', 'Ninguno'), ('atrorvastatina', 'Atorvastatina'), ('colesevelam', 'Colesevelam'), ('colestiramina', 'Colestiramina'), ('colestipol', 'Colestipol'), ('fluvastatina', 'Fluvastatina'), ('lovastatina', 'Lovastatina'), ('pravastatina', 'Pravastatina'), ('rosuvastatina', 'Rosuvastatina')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('tipo_1', 'Tipo 1'), ('tipo_2', 'Tipo 2'), ('gestacional', 'Gestacional'), ('prediabetes', 'Prediabetes')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadesL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('cardiopatias', 'Cardiopatías'), ('cirugias', 'Cirugías'), ('fumador', 'Fumador'), ('hpv', 'HPV'), ('otras', 'Otras')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadesNeuropatias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('si', 'Sí')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadesRespiratorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('asma', 'Asma'), ('bronquitis', 'Bronquitis'), ('enfisema', 'Enfisema'), ('epoc', 'EPOC'), ('hipertension_pulmonar', 'Hipertensión Pulmonar'), ('neumonia', 'Neumonía'), ('rinitis', 'Rinitis'), ('tuberculosis', 'Tuberculosis')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadesReumatologicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('artritis_idiopatica_juvenil', 'Artritis Idiopática Juvenil'), ('artritis_reumatoidea', 'Artritis Reumatoidea'), ('artrosis', 'Artrosis'), ('esclerosis_sistemica', 'Esclerosis Sistémica'), ('espondilitis_anquilosante', 'Espondilitis Anquilosante'), ('fibromialgia', 'Fibromialgia'), ('gota', 'Gota'), ('lumbago_y_ciatico', 'Lumbago y Ciático'), ('lupus', 'Lupus'), ('osteoporosis', 'Osteoporosis'), ('psoriasis', 'Psoriasis'), ('sjogren', 'Sjögren'), ('uveitis', 'Uveitis')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadesVasculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('acv', 'ACV'), ('aneurisma', 'Aneurisma'), ('eap', 'EAP'), ('edema', 'Edema'), ('trombosis', 'Trombosis'), ('varices', 'Varices')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hipertension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('no', 'No'), ('si', 'Si')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HipertensionMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguno', 'Ninguno'), ('Atenolol', 'Atenolol'), ('Benazepril', 'Benazepril'), ('Bisoprolol', 'Bisoprolol'), ('Captopril', 'Captopril'), ('Carvedilol', 'Carvedilol'), ('Cobis5', 'Cobis5'), ('Enalapril', 'Enalapril'), ('Fosinopril', 'Fosinopril'), ('Lisinopril', 'Lisinopril'), ('Lozertan', 'Lozertan'), ('Perindopril', 'Perindopril'), ('Quinapril', 'Quinapril'), ('Ramipril', 'Ramipril'), ('Trandolapril', 'Trandolapril'), ('Valsartan', 'Valsartan'), ('Vasetextend', 'Vasetextend')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentosDiabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguno', 'Ninguno'), ('agonistas', 'Agonistas Receptor GLP-1'), ('glibenclamida', 'Glibenclamida'), ('inhibidores_DDP-4', 'Inhibidores DDP-4'), ('inhibidores_SGLT2', 'Inhibidores SGLT2'), ('insulina', 'Insulina'), ('liraglutida', 'Liraglutida'), ('metformina', 'Metformina'), ('miglitinidas', 'Miglitinidas'), ('saxagliptina', 'Saxagliptina'), ('sitagliptina', 'Sitagliptina'), ('sulfonilureas', 'Sulfonilureas')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatologiasPieDerecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguna', 'Ninguna'), ('ampollas', 'Ampollas'), ('amputaciones', 'Amputaciones'), ('grietas', 'Grietas'), ('helomas', 'Helomas'), ('hiperqueratosis', 'Hiperqueratosis'), ('onicocriptosis', 'Onicocriptosis'), ('onicofosis', 'Onicofosis'), ('onicomicosis', 'Onicomicosis'), ('osteopatias', 'Osteopatías'), ('ulceras', 'Ulceras')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatologiasPieIzquierdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ninguna', 'Ninguna'), ('ampollas', 'Ampollas'), ('amputaciones', 'Amputaciones'), ('grietas', 'Grietas'), ('helomas', 'Helomas'), ('hiperqueratosis', 'Hiperqueratosis'), ('onicocriptosis', 'Onicocriptosis'), ('onicofosis', 'Onicofosis'), ('onicomicosis', 'Onicomicosis'), ('osteopatias', 'Osteopatías'), ('ulceras', 'Ulceras')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_calzado', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('actividad_fisica', models.CharField(choices=[('ninguna', 'Ninguna'), ('baile', 'Baile'), ('bicicleta', 'Bicicleta'), ('caminata', 'Caminata'), ('futbol', 'Futbol'), ('gimnasio', 'Gimnasio'), ('golf', 'Golf'), ('hockey', 'Hockey'), ('kinesio', 'Kinesio'), ('patin', 'Patin'), ('pilates', 'Pilates'), ('rugby', 'Rugby'), ('yoga', 'Yoga'), ('zumba', 'Zumba')], default='ninguna', max_length=20)),
                ('plantillas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=10)),
            ],
            options={
                'verbose_name': 'Perfil Paciente',
                'verbose_name_plural': 'Perfiles Pacientes',
            },
        ),
        migrations.CreateModel(
            name='plantillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plantillas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('normal', 'Normal'), ('cavo', 'Pie Cavo'), ('plano', 'Pie Plano'), ('varo', 'Pie Varo'), ('valgo', 'Pie Valgo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='historiaclinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('fecha_consulta', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diabetes', models.CharField(choices=[('no', 'No'), ('tipo_1', 'Tipo 1'), ('tipo_2', 'Tipo 2'), ('gestacional', 'Gestacional'), ('prediabetes', 'Prediabetes')], default='no', max_length=20)),
                ('medicamentos_diabetes', models.CharField(choices=[('ninguno', 'Ninguno'), ('agonistas', 'Agonistas Receptor GLP-1'), ('glibenclamida', 'Glibenclamida'), ('inhibidores_DDP-4', 'Inhibidores DDP-4'), ('inhibidores_SGLT2', 'Inhibidores SGLT2'), ('insulina', 'Insulina'), ('liraglutida', 'Liraglutida'), ('metformina', 'Metformina'), ('miglitinidas', 'Miglitinidas'), ('saxagliptina', 'Saxagliptina'), ('sitagliptina', 'Sitagliptina'), ('sulfonilureas', 'Sulfonilureas')], default='ninguno', max_length=100)),
                ('tipo_pie_derecho', models.CharField(choices=[('normal', 'Normal'), ('cavo', 'Pie Cavo'), ('plano', 'Pie Plano'), ('varo', 'Pie Varo'), ('valgo', 'Pie Valgo')], default='normal', max_length=20)),
                ('tipo_pie_izquierdo', models.CharField(choices=[('normal', 'Normal'), ('cavo', 'Pie Cavo'), ('plano', 'Pie Plano'), ('varo', 'Pie Varo'), ('valgo', 'Pie Valgo')], default='normal', max_length=20)),
                ('colesterol', models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=20)),
                ('medicamentos_colesterol', models.CharField(choices=[('ninguno', 'Ninguno'), ('atrorvastatina', 'Atorvastatina'), ('colesevelam', 'Colesevelam'), ('colestiramina', 'Colestiramina'), ('colestipol', 'Colestipol'), ('fluvastatina', 'Fluvastatina'), ('lovastatina', 'Lovastatina'), ('pravastatina', 'Pravastatina'), ('rosuvastatina', 'Rosuvastatina')], default='ninguno', max_length=100)),
                ('anticoagulante', models.CharField(choices=[('no', 'No'), ('si', 'Si')], default='no', max_length=20)),
                ('anticoagulante_medicamentos', models.CharField(choices=[('ninguno', 'Ninguno'), ('acetilsalicilico', 'Acetilsalicílico'), ('aspirina', 'Aspirina'), ('heparina', 'Heparina')], default='ninguno', max_length=100)),
                ('hipertension', models.CharField(choices=[('no', 'No'), ('si', 'Si')], default='no', max_length=20)),
                ('hipertension_medicamentos', models.CharField(choices=[('ninguno', 'Ninguno'), ('Atenolol', 'Atenolol'), ('Benazepril', 'Benazepril'), ('Bisoprolol', 'Bisoprolol'), ('Captopril', 'Captopril'), ('Carvedilol', 'Carvedilol'), ('Cobis5', 'Cobis5'), ('Enalapril', 'Enalapril'), ('Fosinopril', 'Fosinopril'), ('Lisinopril', 'Lisinopril'), ('Lozertan', 'Lozertan'), ('Perindopril', 'Perindopril'), ('Quinapril', 'Quinapril'), ('Ramipril', 'Ramipril'), ('Trandolapril', 'Trandolapril'), ('Valsartan', 'Valsartan'), ('Vasetextend', 'Vasetextend')], default='ninguno', max_length=100)),
                ('enfermedades_respiratorias', models.CharField(choices=[('no', 'No'), ('asma', 'Asma'), ('bronquitis', 'Bronquitis'), ('enfisema', 'Enfisema'), ('epoc', 'EPOC'), ('hipertension_pulmonar', 'Hipertensión Pulmonar'), ('neumonia', 'Neumonía'), ('rinitis', 'Rinitis'), ('tuberculosis', 'Tuberculosis')], default='no', max_length=100)),
                ('enfermedades_reumatologicas', models.CharField(choices=[('no', 'No'), ('artritis_idiopatica_juvenil', 'Artritis Idiopática Juvenil'), ('artritis_reumatoidea', 'Artritis Reumatoidea'), ('artrosis', 'Artrosis'), ('esclerosis_sistemica', 'Esclerosis Sistémica'), ('espondilitis_anquilosante', 'Espondilitis Anquilosante'), ('fibromialgia', 'Fibromialgia'), ('gota', 'Gota'), ('lumbago_y_ciatico', 'Lumbago y Ciático'), ('lupus', 'Lupus'), ('osteoporosis', 'Osteoporosis'), ('psoriasis', 'Psoriasis'), ('sjogren', 'Sjögren'), ('uveitis', 'Uveitis')], default='no', max_length=100)),
                ('enfermedades_vasculares', models.CharField(choices=[('no', 'No'), ('acv', 'ACV'), ('aneurisma', 'Aneurisma'), ('eap', 'EAP'), ('edema', 'Edema'), ('trombosis', 'Trombosis'), ('varices', 'Varices')], default='no', max_length=100)),
                ('enfermedades_neuropatias', models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=20)),
                ('archivos', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('alergias', models.ManyToManyField(blank=True, to='aplicacion.alergia')),
                ('enfermedades', models.ManyToManyField(blank=True, to='aplicacion.enfermedadesl')),
                ('patologias_pie_derecho', models.ManyToManyField(blank=True, to='aplicacion.patologiaspiederecho')),
                ('patologias_pie_izquierdo', models.ManyToManyField(blank=True, to='aplicacion.patologiaspieizquierdo')),
                ('perfil_paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica_set', to='aplicacion.perfilpaciente')),
            ],
        ),
    ]
