# Generated by Django 5.1.7 on 2025-10-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_seguimientoconsulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguimientoConsulta',
        ),
    ]
