# Generated by Django 5.1.7 on 2025-10-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_delete_seguimientoconsulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='aplicacion.historiaclinica')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='seguimiento_consulta',
            field=models.ManyToManyField(blank=True, to='aplicacion.seguimientoconsulta'),
        ),
    ]
