# Generated by Django 5.1.7 on 2025-10-28 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_seguimientoconsulta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientoconsulta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Seguimiento de Consulta', 'verbose_name_plural': 'Seguimientos de Consulta'},
        ),
        migrations.AlterField(
            model_name='seguimientoconsulta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
